server:
  port: ":8080"
database:
  host: "postgres"
  port: "5432"
  user: "postgres"
  password: "password"
  dbname: "ariadna"
  sslmode: "disable"
nfcapd:
  directory: "/data/nfcapd/"
  scan_interval: "5m"
auth:
  jwt_secret: "a-very-long-and-secure-secret-key-that-you-must-change"
telegram:
  bot_token: "8300267329:AAFC-qrrWCDEk1gXdncXcv_f7GqP4LzCoVc"
  chat_id: "-4922706074"
  enabled: true
smtp:
  host: "smtp.timeweb.ru"
  port: 2525
  username: "support@snapsend.me"
  password: "tf4mmsjlm6"
  from: "support@snapsend.me"
  from_name: "Ariadna Billing"
  enabled: true