server:
  port: ":8080"
database:
  host: "postgres"
  port: "5432"
  user: "postgres"
  password: "password"
  dbname: "ariadna"
  sslmode: "disable"
nfcapd:
  directory: "/data/nfcapd/"
  scan_interval: "5m"
auth:
  jwt_secret: "a-very-long-and-secure-secret-key-that-you-must-change"